language:
  - "python"

python:
  - "3.6"

install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

script:
  - "source .env"
  - "coverage run -m unittest discover --cover-package=tests/ && coverage report"

after_success:
  - "coveralls"